version: "3.9"

services:
  backend:
    build: .
    container_name: nestjs-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod